<div class="card-group">
  <div class="card">
    <img class="card-img-top" src="https://images.pexels.com/photos/163042/pokemon-pokemon-go-mobile-trends-smartphone-163042.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Api de Pokemon</h5>
      <p class="card-text">La API de Pokémon es una interfaz de programación de aplicaciones (API, por sus siglas en inglés) que proporciona acceso a una amplia variedad de datos relacionados con el mundo de Pokémon. Esta API permite a los desarrolladores acceder a información detallada sobre Pokémon específicos, movimientos, habilidades, estadísticas, tipos, generaciones y más.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
<a href="proyectos/pokemon/index.html" class="btn btn-primary">ver proyecto</a>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://images.pexels.com/photos/205316/pexels-photo-205316.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Ejemplos de componentes Css</h5>
      <p class="card-text">CSS3, o Cascading Style Sheets 3, es la última versión del lenguaje de hojas de estilo en cascada utilizado para definir el aspecto y el formato de un documento HTML. CSS3 es una evolución del CSS original y agrega nuevas funcionalidades y características que permiten a los desarrolladores web diseñar y estilizar páginas web de manera más sofisticada y dinámica.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
<a href="proyectos/cardsCss/index.html" class="btn btn-primary">ver proyecto</a>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://images.pexels.com/photos/11035386/pexels-photo-11035386.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Api Css-tricks</h5>
      <p class="card-text">CSS-Tricks cubre una amplia variedad de temas relacionados con la creación de sitios web, incluyendo técnicas de diseño responsivo, optimización de rendimiento, uso de frameworks y librerías front-end, animaciones y transiciones, entre otros. Además, el sitio también aborda temas relacionados con el desarrollo web en general, como accesibilidad, arquitectura de información y buenas prácticas de desarrollo.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
<a href="proyectos/spa/index.html" class="btn btn-primary">ver proyecto</a>
    </div>
  </div>
</div>
