    <section>
      <h2>Uso del sitio web</h2>
      <p>Al acceder y utilizar el sitio web de Mi Blog, aceptas cumplir con los siguientes términos y condiciones:</p>
      <ol>
        <li>El contenido del sitio web es solo para fines informativos y no constituye asesoramiento profesional.</li>
        <li>No se permite la reproducción, distribución o modificación del contenido sin el consentimiento previo por escrito de los propietarios de Mi Blog.</li>
        <li>Tu uso del sitio web es bajo tu propio riesgo. No nos hacemos responsables de cualquier daño o pérdida que puedas sufrir al utilizar nuestro sitio.</li>
        <li>Pueden haber enlaces a sitios web de terceros en nuestro blog. No nos responsabilizamos del contenido o las políticas de privacidad de esos sitios.</li>
      </ol>
    </section>
    
    <section>
      <h2>Propiedad intelectual</h2>
      <p>Todos los derechos de propiedad intelectual relacionados con el contenido y los materiales presentes en Mi Blog son propiedad de sus respectivos propietarios, a menos que se indique lo contrario.</p>
      <p>No se permite la reproducción, distribución o modificación de ningún contenido del sitio sin el permiso explícito del titular de los derechos de autor.</p>
    </section>
    
    <section>
      <h2>Limitación de responsabilidad</h2>
      <p>En la medida máxima permitida por la ley, no nos hacemos responsables de ningún daño directo, indirecto, incidental, consecuencial o especial que pueda surgir del uso de nuestro sitio web.</p>
      <p>Hacemos todo lo posible para garantizar la exactitud y actualidad del contenido publicado en el blog, pero no ofrecemos garantías ni asumimos responsabilidad por cualquier error o falta de información en el mismo.</p>
    </section>
    
    <section>
      <h2>Modificaciones</h2>
      <p>Nos reservamos el derecho de modificar estos términos y condiciones en cualquier momento sin previo aviso. Cualquier cambio será efectivo inmediatamente después de su publicación en esta página.</p>
    </section>

