<ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link active" href="proyectos/pokemon/index.html">api pokemon</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="proyectos/cardsCss/index.html">cards desing</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="proyectos/spa/index.html">api css-triks</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="proyectos/viewIphone/index.html">store iphone</a>
  </li>
</ul>
