<footer class="bg-light text-center text-lg-start">
    <nav>
      <a class="a" href="/condiciones">Terminos y condiciones</a>
      <a class="a" href="/privacidad">Politica de privacidad</a>
    </nav>
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright
<i class="fas fa-terminal fa-2x""></i>
  </div>
  <!-- Copyright -->
</footer>
