<!-- menu.phtml -->
</nav>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Mi sitio de Mi</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <li class="nav-item <?php echo ($hereIndex) ? 'active':''; ?>">
        <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
<?php echo $here; ?>
      </li>
    <li class="nav-item <?php echo ($herePortafolio) ? 'active':''; ?>">
        <a class="nav-link" href="/portafolio">Portafolio</a>
      </li>
    <li class="nav-item <?php echo ($hereContacto) ? 'active':''; ?>">
        <a class="nav-link" href="/contacto">Contacto</a>
      </li>
    <li class="nav-item <?php echo ($hereAcerca) ? 'active':''; ?>">
        <a class="nav-link" href="/acerca">Acerca</a>
      </li>
    <li class="nav-item <?php echo ($hereBlog) ? 'active':''; ?>">
        <a class="nav-link" href="/blog">Blog</a>
      </li>
    </ul>
  </div>
</nav>
