<style>
.carousel-inner img{
min-height: 300px !important;
max-height: 400px !important;
}
</style>
<div class="container">
<div style="height:400px" id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://images.pexels.com/photos/585418/pexels-photo-585418.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://images.pexels.com/photos/4314622/pexels-photo-4314622.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
    <p class="p">¡Bienvenido a Mi Blog! Aquí encontrarás artículos interesantes sobre diversos temas, desde tecnología hasta viajes y estilo de vida.</p>
    <p class="p">Explora nuestras publicaciones más recientes y descubre contenido relevante y entretenido. Siéntete libre de comentar y compartir tus pensamientos con nosotros.</p>
</div>





        
        <h2 class="t1">Publicaciones recientes</h2>
<div class="container">
  <div class="row">
    <div class="col-sm">
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="pexels image cap">
  <div class="card-body">
    <h5 class="card-title">Aprende a programar title</h5>
    <p class="card-text">Hackeando la matrix: Descifrando los lenguajes de prog ramación</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

    </div>
    <div class="col-sm">
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="pexels image cap">
  <div class="card-body">
    <h5 class="card-title">Aprende a programar title</h5>
    <p class="card-text">Hackeando la matrix: Descifrando los lenguajes de prog ramación</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

    </div>
    <div class="col-sm">
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="https://images.pexels.com/photos/16018144/pexels-photo-16018144/free-photo-of-oscuro-internet-conexion-tecnologia.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="pexels image cap">
  <div class="card-body">
    <h5 class="card-title">Editor de codigo</h5>
    <p class="card-text">Descubre los secretos de Vim: Guía de inicio para prin cipiantes</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

    </div>
  </div>
</div>
