    <main>
<?php 
$numbers = range(1, 10); // Crea un array con números del 1 al 10
$randomNumber = $numbers[array_rand($numbers)]; // Selecciona un número aleatorio del array
?>
  <img src="https://randomuser.me/api/portraits/men/<?php echo $randomNumber; ?>.jpg" alt="Foto de perfil">
      <p>Hola, soy Luis. ¡Bienvenido a Mi Blog!</p>
      <p>En este blog, compartiré mis pensamientos, experiencias y conocimientos sobre diversos temas, como tecnología, viajes y estilo de vida. Mi objetivo es proporcionarte contenido interesante y útil que te inspire y te mantenga informado.</p>
      <p>Soy un apasionado de [tu campo de interés] y he estado escribiendo en línea durante varios años. Mi Blog es mi plataforma para compartir ideas y conectarme con personas con intereses similares.</p>
      <p>Espero que disfrutes explorando Mi Blog y encuentres valor en las publicaciones que comparto. Si tienes alguna pregunta o comentario, no dudes en ponerte en contacto conmigo a través de la página de contacto.</p>
    </section>
    
    <section>
      <h2 class="t2">Mis redes sociales</h2>
      <ul style="color:var(--cl-paragrahp)">
        <li><a class="a" href="https://twitter.com/miblog" target="_blank">Twitter</a></li>
        <li><a class="a" href="https://instagram.com/miblog" target="_blank">Instagram</a></li>
        <li><a class="a" href="https://linkedin.com/in/tunombre" target="_blank">LinkedIn</a></li>
      </ul>
    </main>
